import { createSchemaField } from "@formily/react";
import {
  ArrayItems,
  ArrayTable,
  DatePicker,
  FormCollapse,
  FormGrid,
  FormItem,
  FormLayout,
  FormTab,
  Input,
  NumberPicker,
  Radio,
  Select,
  Space,
  Switch,
  TimePicker,
} from "@formily/antd-v5";
import { Slider } from "antd";
import {
  ApiBaseNameFormItem,
  ApiGroupFormItem,
  ApiHeadersFormItem,
  ApiOriginFormItem,
  BackgroundImageInput,
  BackgroundStyleSetter,
  BorderRadiusStyleSetter,
  BorderStyleSetter,
  BoxShadowStyleSetter,
  BoxStyleSetter,
  CollapseItem,
  ColorInput,
  ColorTypeSelect,
  CornerInput,
  DecoratorPaddingFormItem,
  DepFieldSetFormItem,
  DesignWidthEnumSelect,
  DisplayStyleSetter,
  DrawerSetter,
  FlexStyleSetter,
  FontStyleSetter,
  ImageInput,
  IsDarkThemeSelect,
  JsonInput,
  PositionDecoratorFormItem,
  PositionInput,
  SizeInput,
  ValueInput,
} from "./components";

export const SchemaField = createSchemaField({
  components: {
    FormItem,
    CollapseItem,
    Input,
    ValueInput,
    SizeInput,
    ColorInput,
    ImageInput,

    PositionInput,
    CornerInput,
    BackgroundImageInput,
    BackgroundStyleSetter,
    BoxStyleSetter,
    BorderStyleSetter,
    BorderRadiusStyleSetter,
    DisplayStyleSetter,
    BoxShadowStyleSetter,
    FlexStyleSetter,
    FontStyleSetter,
    DrawerSetter,
    NumberPicker,
    DatePicker,
    TimePicker,
    Select,
    Radio,
    Slider,
    Switch,
    Space,
    ArrayItems,
    ArrayTable,
    FormCollapse,
    FormGrid,
    FormLayout,
    FormTab,
    IsDarkThemeSelect,
    ColorTypeSelect,
    PositionDecoratorFormItem,
    JsonInput,
    DepFieldSetFormItem,
    DecoratorPaddingFormItem,
    ApiBaseNameFormItem,
    ApiGroupFormItem,
    ApiHeadersFormItem,
    ApiOriginFormItem,
    DesignWidthEnumSelect,
  },
});
